% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames*,x11names*}{xcolor}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Module 8: Solutions to Recommended Exercises},
  pdfauthor={Emma Skarstein, Daesoo Lee, Stefanie Muff; Department of Mathematical Sciences, NTNU},
  colorlinks=true,
  linkcolor=Maroon,
  filecolor=Maroon,
  citecolor=Blue,
  urlcolor=blue,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{Module 8: Solutions to Recommended Exercises}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{TMA4268 Statistical Learning V2022}
\author{Emma Skarstein, Daesoo Lee, Stefanie Muff \and Department of
Mathematical Sciences, NTNU}
\date{March 7, 2022}

\begin{document}
\maketitle

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{problem-1-theoretical}{%
\subsection{Problem 1 -- Theoretical}\label{problem-1-theoretical}}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\tightlist
\item
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \emph{Recursive binary splitting}: We find the best single
  partitioning of the data such that the reduction of RSS is the
  greatest. This process is applied sequencially to each of the split
  parts until a predefined minimum number of leave observation is
  reached.
\item
  \emph{Cost complexity pruning} of the large tree from previoius step,
  in order to obtain a sequence of best trees as a function of a
  parameter \(\alpha\). Each value of \(\alpha\) corresponds to a
  subtree that minimize the following equation (several \(\alpha\)s for
  the same tree):
\end{enumerate}

\[\sum_{m=1}^{|T|}\sum_{i:x_i\in R_m}(y_i - \hat y_{R_m})^2 + \alpha |T|,\]

where \(|T|\) is the numb er of terminal nodes.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  \emph{\(K\)-fold cross-validation} to choose \(\alpha\). For each
  fold:
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Repeat Steps 1 and 2 on all but the kth folds of the training data.
\item
  Evaluate the mean squared prediction on the data in the left-out kth
  fold, as a function of \(\alpha\).
\item
  Average the results for each value of \(\alpha\) and choose \(\alpha\)
  to minimize the average error.
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  Return the subtree from Step 2 that corresponds to the chosen value of
  \(\alpha.\)
\end{enumerate}

For a \textbf{classification} tree we replace RSS with Gini index or
entropy.

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
\end{enumerate}

\(\color{green}{\text{Advantages}}\)

\begin{itemize}
\item
  Very easy to explain
\item
  Can be displayed graphically
\item
  Can handle both quantitative and qualitative predictors without the
  need to create dummy variables
\end{itemize}

\(\color{red}{\text{Disadvantages}}\)

\begin{itemize}
\item
  The predictive accuracy is usualy not very high
\item
  They are non-robust. That is a small change in the data can cause a
  large change in the estimated tree
\end{itemize}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
\end{enumerate}

Decision trees suffer from high variance. Recall that if we have \(B\)
\(i.i.d\) observations of a random variable \(X\) with the same mean and
variance \(\sigma^2.\) We calculate the mean
\(\bar{X} = \frac{1}{B} \sum_{b=1}^B X_b,\) and the variance of the mean
is \(\text{Var}(\bar{X}) = \frac{\sigma^2}{B}.\) That is by averaging we
get reduced variance.

For decision trees, if we have \(B\) training sets, we could estimate
\(\hat{f}_1({\boldsymbol x}),\hat{f}_2({\boldsymbol x}),\ldots, \hat{f}_B({\boldsymbol x})\)
and average them as
\[\hat{f}_{avg}({\boldsymbol x})=\frac{1}{B}\sum_{b=1}^B \hat{f}_b({\boldsymbol x}) \ .\]
However we do not have many data independent data sets, and we
bootstraping to create \(B\) datasets. These datasets are however not
completely independent and the reduction in variance is therefore not as
large as for independent training sets.

To make the different trees that are built from each bootstrapped
dataset more different, random forests use a random subset of the
predictors to split the tree into new branches at each step. This
decorrelates the different trees that are built from the \(B\)
bootstrapped datasets, and consequently reduces variance.

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{3}
\item
  An OOB is the set of observations that were not chosen to be in a
  specific bootstrap sample. From RecEx5-Problem 4c we have that on
  average \(1-0.632 = 0.368\) are included in the OOB sample.
\item
\end{enumerate}

\textbf{Variable importance based on node impurity}

\textbf{Regression Trees}: The total amount that the RSS is decreased
due to splits of each predictor, averaged over the B trees.

\textbf{Classification Trees}: The importance is the mean decrease (over
all B trees) in the Gini index by splits of a predictor.

\textbf{Variable importance based on randomization}

This measure is based on how much the predictive accuracy (MSE or gini
indiex) is decreased when the variable is replaced by a permuted version
of it. You find a drawing
\href{https://github.com/stefaniemuff/statlearning/blob/master/8Trees/M8_variableImportanceRandomization.pdf}{here}.

\hypertarget{problem-2-regression-book-ex.-8}{%
\subsection{Problem 2 -- Regression (Book Ex.
8)}\label{problem-2-regression-book-ex.-8}}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ISLR)}
\FunctionTok{data}\NormalTok{(}\StringTok{"Carseats"}\NormalTok{)}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{4268}\NormalTok{)}
\NormalTok{n }\OtherTok{=} \FunctionTok{nrow}\NormalTok{(Carseats)}
\NormalTok{train }\OtherTok{=} \FunctionTok{sample}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\NormalTok{n, }\FloatTok{0.7} \SpecialCharTok{*} \FunctionTok{nrow}\NormalTok{(Carseats), }\AttributeTok{replace =}\NormalTok{ F)}
\NormalTok{test }\OtherTok{=}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{:}\NormalTok{n)[}\SpecialCharTok{{-}}\NormalTok{train]}
\NormalTok{Carseats.train }\OtherTok{=}\NormalTok{ Carseats[train, ]}
\NormalTok{Carseats.test }\OtherTok{=}\NormalTok{ Carseats[}\SpecialCharTok{{-}}\NormalTok{train, ]}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tree)}
\NormalTok{tree.mod }\OtherTok{=} \FunctionTok{tree}\NormalTok{(Sales }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., Carseats, }\AttributeTok{subset =}\NormalTok{ train)}
\FunctionTok{summary}\NormalTok{(tree.mod)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Regression tree:
## tree(formula = Sales ~ ., data = Carseats, subset = train)
## Variables actually used in tree construction:
## [1] "ShelveLoc"   "Price"       "Age"         "Income"      "CompPrice"  
## [6] "Population"  "Advertising" "Education"  
## Number of terminal nodes:  18 
## Residual mean deviance:  2.609 = 683.6 / 262 
## Distribution of residuals:
##     Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
## -3.74000 -1.12400 -0.06522  0.00000  1.06800  4.47200
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(tree.mod)}
\FunctionTok{text}\NormalTok{(tree.mod, }\AttributeTok{pretty =} \DecValTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics[width=0.7\linewidth]{RecEx8-sol_files/figure-latex/unnamed-chunk-3-1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{yhat }\OtherTok{=} \FunctionTok{predict}\NormalTok{(tree.mod, }\AttributeTok{newdata =}\NormalTok{ Carseats.test)}
\NormalTok{mse }\OtherTok{=} \FunctionTok{mean}\NormalTok{((yhat }\SpecialCharTok{{-}}\NormalTok{ Carseats.test}\SpecialCharTok{$}\NormalTok{Sales)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\NormalTok{mse}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4.585249
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{4268}\NormalTok{)}
\NormalTok{cv.Carseats }\OtherTok{=} \FunctionTok{cv.tree}\NormalTok{(tree.mod)}
\NormalTok{tree.min }\OtherTok{=} \FunctionTok{which.min}\NormalTok{(cv.Carseats}\SpecialCharTok{$}\NormalTok{dev)}
\NormalTok{best }\OtherTok{=}\NormalTok{ cv.Carseats}\SpecialCharTok{$}\NormalTok{size[tree.min]}
\FunctionTok{plot}\NormalTok{(cv.Carseats}\SpecialCharTok{$}\NormalTok{size, cv.Carseats}\SpecialCharTok{$}\NormalTok{dev, }\AttributeTok{type =} \StringTok{"b"}\NormalTok{)}
\FunctionTok{points}\NormalTok{(cv.Carseats}\SpecialCharTok{$}\NormalTok{size[tree.min], cv.Carseats}\SpecialCharTok{$}\NormalTok{dev[tree.min], }\AttributeTok{col =} \StringTok{"red"}\NormalTok{, }\AttributeTok{pch =} \DecValTok{20}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{RecEx8-sol_files/figure-latex/unnamed-chunk-4-1.pdf}

We see that trees with sizes 11, 12, 16 and 17 have similar deviance
values. We might choose the tree of size 11 as it gives the simpler
tree.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pr.tree }\OtherTok{=} \FunctionTok{prune.tree}\NormalTok{(tree.mod, }\AttributeTok{best =} \DecValTok{11}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(pr.tree)}
\FunctionTok{text}\NormalTok{(pr.tree, }\AttributeTok{pretty =} \DecValTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics[width=0.7\linewidth]{RecEx8-sol_files/figure-latex/unnamed-chunk-5-1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{yhat }\OtherTok{=} \FunctionTok{predict}\NormalTok{(pr.tree, }\AttributeTok{newdata =}\NormalTok{ Carseats.test)}
\NormalTok{mse }\OtherTok{=} \FunctionTok{mean}\NormalTok{((yhat }\SpecialCharTok{{-}}\NormalTok{ Carseats.test}\SpecialCharTok{$}\NormalTok{Sales)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\NormalTok{mse}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4.378499
\end{verbatim}

There is a slight reducten in MSE for the pruned tree with 11 leaves.

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{3}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(randomForest)}
\FunctionTok{dim}\NormalTok{(Carseats)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 400  11
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{bag.Carseats }\OtherTok{=} \FunctionTok{randomForest}\NormalTok{(Sales }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., Carseats.train, }\AttributeTok{mtry =} \FunctionTok{ncol}\NormalTok{(Carseats) }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{,}
    \AttributeTok{ntree =} \DecValTok{500}\NormalTok{, }\AttributeTok{importance =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{yhat.bag }\OtherTok{=} \FunctionTok{predict}\NormalTok{(bag.Carseats, }\AttributeTok{newdata =}\NormalTok{ Carseats.test)}
\NormalTok{mse.bag }\OtherTok{=} \FunctionTok{mean}\NormalTok{((yhat.bag }\SpecialCharTok{{-}}\NormalTok{ Carseats.test}\SpecialCharTok{$}\NormalTok{Sales)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\NormalTok{mse.bag}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.122958
\end{verbatim}

Bagging decreases the test MSE significantly to 2.12. From the
importance plots we might conclude that \texttt{Price}and
\texttt{ShelveLoc} are the most important Variables.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{importance}\NormalTok{(bag.Carseats)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##               %IncMSE IncNodePurity
## CompPrice   26.803869    218.740455
## Income      10.284817    127.447480
## Advertising 25.795425    196.438893
## Population   6.084270     92.149065
## Price       67.791459    667.696518
## ShelveLoc   75.485534    734.902022
## Age         24.961130    229.491494
## Education    3.423565     64.510742
## Urban       -1.373635      9.423406
## US           3.141449     10.105870
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{varImpPlot}\NormalTok{(bag.Carseats)}
\end{Highlighting}
\end{Shaded}

\includegraphics[width=0.8\linewidth]{RecEx8-sol_files/figure-latex/unnamed-chunk-8-1}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{4}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rf.Carseats }\OtherTok{=} \FunctionTok{randomForest}\NormalTok{(Sales }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data =}\NormalTok{ Carseats.train, }\AttributeTok{mtry =} \DecValTok{3}\NormalTok{, }\AttributeTok{ntree =} \DecValTok{500}\NormalTok{,}
    \AttributeTok{importance =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{yhat.rf }\OtherTok{=} \FunctionTok{predict}\NormalTok{(rf.Carseats, }\AttributeTok{newdata =}\NormalTok{ Carseats.test)}
\NormalTok{mse\_forest }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{((yhat.rf }\SpecialCharTok{{-}}\NormalTok{ Carseats.test}\SpecialCharTok{$}\NormalTok{Sales)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\NormalTok{mse\_forest}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.25397
\end{verbatim}

We use \(p/3 = 10/3 \approx 3\) trees, and we obtain an MSE of 2.25
which is slightly larger than Bagging MSE. The two most important
Variables are again \texttt{Price}and \texttt{ShelveLoc}.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{importance}\NormalTok{(rf.Carseats)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##               %IncMSE IncNodePurity
## CompPrice   15.789484     211.79213
## Income       5.415374     174.79625
## Advertising 18.402600     210.47149
## Population   1.076874     148.09993
## Price       45.548596     577.68865
## ShelveLoc   47.810006     549.62278
## Age         15.936114     241.99130
## Education    3.275725     104.89503
## Urban       -1.646580      19.63668
## US           5.427599      36.45647
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{varImpPlot}\NormalTok{(rf.Carseats)}
\end{Highlighting}
\end{Shaded}

\includegraphics[width=0.8\linewidth]{RecEx8-sol_files/figure-latex/unnamed-chunk-10-1}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{5}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(gbm)}
\NormalTok{r.boost }\OtherTok{=} \FunctionTok{gbm}\NormalTok{(Sales }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., Carseats.train, }\AttributeTok{distribution =} \StringTok{"gaussian"}\NormalTok{, }\AttributeTok{n.trees =} \DecValTok{500}\NormalTok{,}
    \AttributeTok{interaction.depth =} \DecValTok{4}\NormalTok{, }\AttributeTok{shrinkage =} \FloatTok{0.1}\NormalTok{)}
\NormalTok{yhat.boost }\OtherTok{=} \FunctionTok{predict}\NormalTok{(r.boost, }\AttributeTok{newdata =}\NormalTok{ Carseats.test, }\AttributeTok{n.trees =} \DecValTok{500}\NormalTok{)}
\NormalTok{mse\_boost }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{((yhat.boost }\SpecialCharTok{{-}}\NormalTok{ Carseats.test}\SpecialCharTok{$}\NormalTok{Sales)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\NormalTok{mse\_boost}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.151292
\end{verbatim}

We see a further decrease in MSE by boosing our trees.

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{6}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{train.predictors }\OtherTok{=}\NormalTok{ Carseats.train[, }\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{]}
\NormalTok{test.predictors }\OtherTok{=}\NormalTok{ Carseats.test[, }\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{]}
\NormalTok{Y.train }\OtherTok{=}\NormalTok{ Carseats.train[, }\DecValTok{1}\NormalTok{]}
\NormalTok{Y.test }\OtherTok{=}\NormalTok{ Carseats.test[, }\DecValTok{1}\NormalTok{]}

\NormalTok{bag.Car }\OtherTok{=} \FunctionTok{randomForest}\NormalTok{(train.predictors, }\AttributeTok{y =}\NormalTok{ Y.train, }\AttributeTok{xtest =}\NormalTok{ test.predictors, }\AttributeTok{ytest =}\NormalTok{ Y.test,}
    \AttributeTok{mtry =} \DecValTok{10}\NormalTok{, }\AttributeTok{ntree =} \DecValTok{500}\NormalTok{)}
\NormalTok{rf.Car }\OtherTok{=} \FunctionTok{randomForest}\NormalTok{(train.predictors, }\AttributeTok{y =}\NormalTok{ Y.train, }\AttributeTok{xtest =}\NormalTok{ test.predictors, }\AttributeTok{ytest =}\NormalTok{ Y.test,}
    \AttributeTok{mtry =} \DecValTok{3}\NormalTok{, }\AttributeTok{ntree =} \DecValTok{500}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{500}\NormalTok{, bag.Car}\SpecialCharTok{$}\NormalTok{test}\SpecialCharTok{$}\NormalTok{mse, }\AttributeTok{col =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{type =} \StringTok{"l"}\NormalTok{, }\AttributeTok{xlab =} \StringTok{"Number of Trees"}\NormalTok{,}
    \AttributeTok{ylab =} \StringTok{"Test MSE"}\NormalTok{, }\AttributeTok{ylim =} \FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\FloatTok{2.8}\NormalTok{))}
\FunctionTok{lines}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{500}\NormalTok{, rf.Car}\SpecialCharTok{$}\NormalTok{test}\SpecialCharTok{$}\NormalTok{mse, }\AttributeTok{col =} \StringTok{"green"}\NormalTok{)}

\FunctionTok{legend}\NormalTok{(}\StringTok{"topright"}\NormalTok{, }\FunctionTok{c}\NormalTok{(}\StringTok{"m = p"}\NormalTok{, }\StringTok{"m = p/3"}\NormalTok{), }\AttributeTok{col =} \FunctionTok{c}\NormalTok{(}\StringTok{"blue"}\NormalTok{, }\StringTok{"green"}\NormalTok{), }\AttributeTok{cex =} \DecValTok{1}\NormalTok{, }\AttributeTok{lty =} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics[width=0.7\linewidth]{RecEx8-sol_files/figure-latex/unnamed-chunk-12-1}

\hypertarget{problem-3-classification}{%
\subsection{Problem 3 --
Classification}\label{problem-3-classification}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(kernlab)}
\FunctionTok{data}\NormalTok{(spam)}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\StringTok{\textasciigrave{}}\AttributeTok{?}\StringTok{\textasciigrave{}}\NormalTok{(spam)}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ISLR)}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{4268}\NormalTok{)}
\NormalTok{n }\OtherTok{=} \FunctionTok{nrow}\NormalTok{(spam)}
\NormalTok{train }\OtherTok{=} \FunctionTok{sample}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\NormalTok{n, }\FloatTok{0.7} \SpecialCharTok{*}\NormalTok{ n, }\AttributeTok{replace =}\NormalTok{ F)}
\NormalTok{test }\OtherTok{=}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{:}\NormalTok{n)[}\SpecialCharTok{{-}}\NormalTok{train]}
\NormalTok{spam.train }\OtherTok{=}\NormalTok{ spam[train, ]}
\NormalTok{spam.test }\OtherTok{=}\NormalTok{ spam[}\SpecialCharTok{{-}}\NormalTok{train, ]}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{spam.tree }\OtherTok{=} \FunctionTok{tree}\NormalTok{(type }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., spam, }\AttributeTok{subset =}\NormalTok{ train)}

\FunctionTok{plot}\NormalTok{(spam.tree)}
\FunctionTok{text}\NormalTok{(spam.tree, }\AttributeTok{pretty =} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics[width=0.7\linewidth]{RecEx8-sol_files/figure-latex/unnamed-chunk-16-1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(spam.tree)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Classification tree:
## tree(formula = type ~ ., data = spam, subset = train)
## Variables actually used in tree construction:
## [1] "charExclamation" "remove"          "charDollar"      "george"         
## [5] "hp"              "capitalLong"     "our"             "capitalAve"     
## [9] "hpl"            
## Number of terminal nodes:  14 
## Residual mean deviance:  0.4801 = 1539 / 3206 
## Misclassification error rate: 0.08975 = 289 / 3220
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{3}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{yhat }\OtherTok{=} \FunctionTok{predict}\NormalTok{(spam.tree, spam[test, ], }\AttributeTok{type =} \StringTok{"class"}\NormalTok{)}
\NormalTok{response.test }\OtherTok{=}\NormalTok{ spam}\SpecialCharTok{$}\NormalTok{type[test]}

\NormalTok{misclass }\OtherTok{=} \FunctionTok{table}\NormalTok{(yhat, response.test)}
\NormalTok{misclass}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          response.test
## yhat      nonspam spam
##   nonspam     781   67
##   spam         67  466
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{1} \SpecialCharTok{{-}} \FunctionTok{sum}\NormalTok{(}\FunctionTok{diag}\NormalTok{(misclass))}\SpecialCharTok{/}\FunctionTok{sum}\NormalTok{(misclass)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.09703114
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{4}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{4268}\NormalTok{)}

\NormalTok{cv.spam }\OtherTok{=} \FunctionTok{cv.tree}\NormalTok{(spam.tree, }\AttributeTok{FUN =}\NormalTok{ prune.misclass)}

\FunctionTok{plot}\NormalTok{(cv.spam}\SpecialCharTok{$}\NormalTok{size, cv.spam}\SpecialCharTok{$}\NormalTok{dev, }\AttributeTok{type =} \StringTok{"b"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics[width=0.7\linewidth]{RecEx8-sol_files/figure-latex/unnamed-chunk-18-1}

According to the plot the optimal number of terminal nodes is 6 (or
larger). We choose 6 as this gives the simplest tree, and prune the tree
according to this value.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{prune.spam }\OtherTok{=} \FunctionTok{prune.misclass}\NormalTok{(spam.tree, }\AttributeTok{best =} \DecValTok{6}\NormalTok{)}

\FunctionTok{plot}\NormalTok{(prune.spam)}
\FunctionTok{text}\NormalTok{(prune.spam, }\AttributeTok{pretty =} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics[width=0.7\linewidth]{RecEx8-sol_files/figure-latex/unnamed-chunk-19-1}

We predict the response for the test data:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{yhat.prune }\OtherTok{=} \FunctionTok{predict}\NormalTok{(prune.spam, spam[test, ], }\AttributeTok{type =} \StringTok{"class"}\NormalTok{)}

\NormalTok{misclass.prune }\OtherTok{=} \FunctionTok{table}\NormalTok{(yhat.prune, response.test)}
\NormalTok{misclass.prune}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           response.test
## yhat.prune nonspam spam
##    nonspam     796  104
##    spam         52  429
\end{verbatim}

The misclassification rate is

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{1} \SpecialCharTok{{-}} \FunctionTok{sum}\NormalTok{(}\FunctionTok{diag}\NormalTok{(misclass.prune))}\SpecialCharTok{/}\FunctionTok{sum}\NormalTok{(misclass.prune)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1129616
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{5}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(randomForest)}
\NormalTok{bag.spam }\OtherTok{=} \FunctionTok{randomForest}\NormalTok{(type }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data =}\NormalTok{ spam, }\AttributeTok{subset =}\NormalTok{ train, }\AttributeTok{mtry =} \FunctionTok{ncol}\NormalTok{(spam) }\SpecialCharTok{{-}}
    \DecValTok{1}\NormalTok{, }\AttributeTok{ntree =} \DecValTok{500}\NormalTok{, }\AttributeTok{importance =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

We predict the response for the test data as before:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{yhat.bag }\OtherTok{=} \FunctionTok{predict}\NormalTok{(bag.spam, }\AttributeTok{newdata =}\NormalTok{ spam[test, ])}

\NormalTok{misclass.bag }\OtherTok{=} \FunctionTok{table}\NormalTok{(yhat.bag, response.test)}
\NormalTok{misclass.bag}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          response.test
## yhat.bag  nonspam spam
##   nonspam     810   43
##   spam         38  490
\end{verbatim}

The misclassification rate is

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{1} \SpecialCharTok{{-}} \FunctionTok{sum}\NormalTok{(}\FunctionTok{diag}\NormalTok{(misclass.bag))}\SpecialCharTok{/}\FunctionTok{sum}\NormalTok{(misclass.bag)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.05865315
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{6}
\tightlist
\item
\end{enumerate}

We now use the random forest-algorithm and consider only
\(\sqrt{57}\approx 8\) of the predictors at each split. This is
specified in \texttt{mtry}.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{4268}\NormalTok{)}
\NormalTok{rf.spam }\OtherTok{=} \FunctionTok{randomForest}\NormalTok{(type }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data =}\NormalTok{ spam, }\AttributeTok{subset =}\NormalTok{ train, }\AttributeTok{mtry =} \FunctionTok{round}\NormalTok{(}\FunctionTok{sqrt}\NormalTok{(}\FunctionTok{ncol}\NormalTok{(spam) }\SpecialCharTok{{-}}
    \DecValTok{1}\NormalTok{)), }\AttributeTok{ntree =} \DecValTok{500}\NormalTok{, }\AttributeTok{importance =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

We study the importance of each variable

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{importance}\NormalTok{(rf.spam)}
\end{Highlighting}
\end{Shaded}

If \texttt{MeanDecreaseAccuracy} and \texttt{MeanDecreaseGini} are
large, the corresponding covariate is important.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{varImpPlot}\NormalTok{(rf.spam)}
\end{Highlighting}
\end{Shaded}

\includegraphics[width=0.9\linewidth]{RecEx8-sol_files/figure-latex/unnamed-chunk-27-1}

In this plot we see that \texttt{charExclamation} is the most important
covariate, followed by \texttt{remove} and \texttt{charDollar}. This is
as expected as these variables are used in the top splits in the
classification trees we have seen so far.

We now predict the response for the test data.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{yhat.rf }\OtherTok{=} \FunctionTok{predict}\NormalTok{(rf.spam, }\AttributeTok{newdata =}\NormalTok{ spam[test, ])}

\NormalTok{misclass.rf }\OtherTok{=} \FunctionTok{table}\NormalTok{(yhat.rf, response.test)}
\DecValTok{1} \SpecialCharTok{{-}} \FunctionTok{sum}\NormalTok{(}\FunctionTok{diag}\NormalTok{(misclass.rf))}\SpecialCharTok{/}\FunctionTok{sum}\NormalTok{(misclass.rf)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.044895
\end{verbatim}

The misclassification rate is given by

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{misclass.rf}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          response.test
## yhat.rf   nonspam spam
##   nonspam     824   38
##   spam         24  495
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{7}
\tightlist
\item
\end{enumerate}

The \texttt{gbm()} function does not allow factors, so we have to use
`1' and `0' instead of \texttt{spam} and \texttt{nonspam}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(gbm)}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{4268}\NormalTok{)}

\NormalTok{spamboost }\OtherTok{=}\NormalTok{ spam}
\NormalTok{spamboost}\SpecialCharTok{$}\NormalTok{type }\OtherTok{=} \FunctionTok{c}\NormalTok{()}
\NormalTok{spamboost}\SpecialCharTok{$}\NormalTok{type[spam}\SpecialCharTok{$}\NormalTok{type }\SpecialCharTok{==} \StringTok{"spam"}\NormalTok{] }\OtherTok{=} \DecValTok{1}
\NormalTok{spamboost}\SpecialCharTok{$}\NormalTok{type[spam}\SpecialCharTok{$}\NormalTok{type }\SpecialCharTok{==} \StringTok{"nonspam"}\NormalTok{] }\OtherTok{=} \DecValTok{0}

\NormalTok{boost.spam }\OtherTok{=} \FunctionTok{gbm}\NormalTok{(type }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data =}\NormalTok{ spamboost[train, ], }\AttributeTok{distribution =} \StringTok{"bernoulli"}\NormalTok{,}
    \AttributeTok{n.trees =} \DecValTok{5000}\NormalTok{, }\AttributeTok{interaction.depth =} \DecValTok{3}\NormalTok{, }\AttributeTok{shrinkage =} \FloatTok{0.001}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

We predict the response for the test data

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{yhat.boost }\OtherTok{=} \FunctionTok{predict}\NormalTok{(boost.spam, }\AttributeTok{newdata =}\NormalTok{ spamboost[}\SpecialCharTok{{-}}\NormalTok{train, ], }\AttributeTok{n.trees =} \DecValTok{5000}\NormalTok{, }\AttributeTok{distribution =} \StringTok{"bernoulli"}\NormalTok{,}
    \AttributeTok{type =} \StringTok{"response"}\NormalTok{)}

\NormalTok{yhat.boost }\OtherTok{=} \FunctionTok{ifelse}\NormalTok{(yhat.boost }\SpecialCharTok{\textgreater{}} \FloatTok{0.5}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)  }\CommentTok{\#Transform to 0 and 1 (nonspam and spam).}

\NormalTok{misclass.boost }\OtherTok{=} \FunctionTok{table}\NormalTok{(yhat.boost, spamboost}\SpecialCharTok{$}\NormalTok{type[test])}

\NormalTok{misclass.boost}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           
## yhat.boost   0   1
##          0 812  52
##          1  36 481
\end{verbatim}

and the misclassification rate is

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{1} \SpecialCharTok{{-}} \FunctionTok{sum}\NormalTok{(}\FunctionTok{diag}\NormalTok{(misclass.boost))}\SpecialCharTok{/}\FunctionTok{sum}\NormalTok{(misclass.boost)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.06372194
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\tightlist
\item
\end{enumerate}

We get lower missclassification rates for bagging, random forest and
boosting than for a simple tree, which is expected.

\end{document}
