---
subtitle: "TMA4268 Statistical Learning V2023"
title: "Compulsory exercise 1: Group XYZ (add your group number here)"
author: "NN1, NN2 and NN3 (full names of all group members)"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  # html_document
  pdf_document
---
  
```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE,tidy=TRUE,message=FALSE,warning=FALSE,strip.white=TRUE,prompt=FALSE,
                      cache=TRUE, size="scriptsize",fig.width=4, fig.height=3,fig.align = "center")

```

```{r,eval=FALSE,echo=TRUE}
install.packages("knitr")     # probably already installed
install.packages("rmarkdown") # probably already installed
install.packages("ggplot2")   # plotting with ggplot2
install.packages("dplyr")     # for data cleaning and preparation
install.packages("tidyr")     # also data preparation
install.packages("carData")   # dataset
install.packages("class")     # for KNN
install.packages("pROC")      # calculate roc
install.packages("plotROC")   # plot roc
install.packages("ggmosaic")  # mosaic plot
```

<!--  Etc (load all packages needed). -->


# Problem 1

For this problem you will need to include some LaTex code. Please install latex on your computer and then consult Compulsor1.Rmd for hints how to write formulas in LaTex.

## a)

## b)

## c)

## d)

## e)

 

# Problem 2

Here is a code chunk:

```{r desc, fig.width=6, fig.height=6, fig.cap="Pairs plot of the academic salary data set."}
library(carData)

?Salaries

GGally::ggpairs(Salaries)
```


## a)

## b) 
 
## c)


# Problem 3

# Problem 4
 
